### ISSUE TITLE
ip什么时候更新？

### ISSUE THREAD

**Issue by xjtushilei** [ganlvtech/ip-xjtu#1]
202.117.54.8x左右一些列都是我们在使用的。现在是在东二楼三楼在使用

**Comment by ganlvtech** [comment]
这个是不是官方的ip列表，这个数据可能是几年前的了，我不保证准确性。2015年-2016年学校的网络进行过改造，大部分机器已经不是固定IP地址了，即使固定也可能有所修改，所以这个csv列表现在可能并没有什么实际意义。虽然对应关系已经变了，但是ip地址还是属于交大的，这个列表只能判断一个ip是否属于交大。我可以在README中加上说明，表明ip归属地不准确。

欢迎提建议，或提交Pull Request。

**Comment by ganlvtech** [comment]
这个仓库主要用于判断是否是校内访问，一些校内专享的内容是禁止外部ip访问的，服务器一般也是会禁止外部ip访问的。
